using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BaseAPI.BAL.Mesagges
{
    public enum BussinesMesageList
    {
        /***CODIGOS GENERICOS****/
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_SATISFACTORIA_1 = 1,
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_REGISTRO_NO_EXISTE_2 = 2,
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_DATOS_ACTUALIZADOS_CON_EXITO_3 = 3,
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_LISTADEVISITAS_ACTUALIZADOS_CON_EXITO_4 = 4,
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_CHECKLISTTYPE_NO_EXISTE_5 = 5,
        CONST_BASEAPI_CODIGO_RESPUESTA_GENERAL_SITE_NO_EXISTE_6 = 6,


        /***CODIGOS ESPECIFICOS DEL MICROSERVICIO - DOMINIO CLIENTE****/
        CONST_BASEAPI_CODIGO_RESPUESTA_CLIENTE_YA_NO_ES_CLIENTE_1000 = 1000,
        CONST_BASEAPI_CODIGO_RESPUESTA_CLIENTE_YA_EXISTE_1001 = 1001,

        


        /***CODIGOS ESPECIFICOS DEL MICROSERVICIO - DOMINIO POSTES****/

        CONST_BASEAPI_CODIGO_RESPUESTA_POSTE_NO_FUERA_SERVICIO_2000 = 2000,

        /***CODIGOS ESPECIFICOS DEL MICROSERVICIO - DOMINIO USUARIOS****/

        CONST_BASEAPI_CODIGO_RESPUESTA_USUARIO_NO_EXISTE_3000 = 3000,
        CONST_BASEAPI_CODIGO_RESPUESTA_CLAVE_INCORRECTA_3001 = 3001,
        CONST_BASEAPI_CODIGO_RESPUESTA_USUARIO_BLOQUEADO_3002 = 3002,
        CONST_BASEAPI_CODIGO_RESPUESTA_CLAVE_VENCIDA_3003 = 3003,
        CONST_BASEAPI_CODIGO_RESPUESTA_ACCESO_DENEGADO_3004 = 3004,
        CONST_BASEAPI_CODIGO_RESPUESTA_SIN_ROLES_ASIGNADOS_3005 = 3005,

        /***CODIGOS ESPECIFICOS DEL MICROSERVICIO - DOMINIO GEOGRAFIA****/
        CONST_BASEAPI_CODIGO_RESPUESTA_PAIS_YA_EXISTE_1001 = 4000,



    }
}
